[theme]
primaryColor = "#6f887a"          # Color de botones, sliders, etc.
backgroundColor = "#c0dccc"       # Color del fondo principal
secondaryBackgroundColor = "#91be8c" # Color de la barra lateral y widgets
textColor = "#000000"             # Color del texto
font = "sans serif"               # Opciones: "sans serif", "serif" o "monospace"